import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  User,
  FileSearch,
  FileText,
  Target,
  MessageSquare,
  Mail,
  Scale,
  CheckSquare,
  Gavel,
  BookOpen,
  Settings,
  Users,
  Calendar,
  Briefcase,
  UserCircle,
  CreditCard,
  BarChart3,
} from "lucide-react";
import type { Role } from "@/domain/auth/roles";
import { ROLES } from "@/domain/auth/roles";

export interface NavItem {
  key: string;
  label: string;
  /** Key into translations.nav for i18n lookup */
  navKey: keyof import("@/i18n/types").Translations["nav"];
  path: string;
  icon: LucideIcon;
  rolesAllowed: Role[];
}

export const NAV_ITEMS: NavItem[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    navKey: "dashboard",
    path: "/dashboard",
    icon: LayoutDashboard,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.TEACHER_THERAPIST, ROLES.ADMIN],
  },
  {
    key: "counselor-dashboard",
    label: "Dashboard",
    navKey: "counselorDashboard",
    path: "/counselor/dashboard",
    icon: LayoutDashboard,
    rolesAllowed: [ROLES.COUNSELOR],
  },
  {
    key: "counselor-appointments",
    label: "Appointments",
    navKey: "counselorAppointments",
    path: "/counselor/appointments",
    icon: MessageSquare,
    rolesAllowed: [ROLES.COUNSELOR],
  },
  {
    key: "counselor-availability",
    label: "Availability",
    navKey: "counselorAvailability",
    path: "/counselor/availability",
    icon: Calendar,
    rolesAllowed: [ROLES.COUNSELOR],
  },
  {
    key: "counselor-services",
    label: "My Services",
    navKey: "counselorServices",
    path: "/counselor/services",
    icon: Briefcase,
    rolesAllowed: [ROLES.COUNSELOR],
  },
  {
    key: "counselor-profile",
    label: "Settings",
    navKey: "counselorProfile",
    path: "/counselor/profile",
    icon: UserCircle,
    rolesAllowed: [ROLES.COUNSELOR],
  },
  {
    key: "child-profile",
    label: "Child Profile",
    navKey: "childProfile",
    path: "/child-profile",
    icon: User,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.ADMIN],
  },
  {
    key: "iep-analyzer",
    label: "IEP Analyzer",
    navKey: "iepAnalyzer",
    path: "/iep/analyse",
    icon: FileSearch,
    rolesAllowed: [ROLES.PARENT, ROLES.ADMIN],
  },
  {
    key: "iep-list",
    label: "IEP Documents",
    navKey: "iepDocuments",
    path: "/iep/list",
    icon: FileText,
    rolesAllowed: [ROLES.PARENT, ROLES.ADMIN],
  },
  {
    key: "goal-progress",
    label: "Goal Progress",
    navKey: "goalProgress",
    path: "/goal-progress",
    icon: Target,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.TEACHER_THERAPIST, ROLES.ADMIN],
  },
  // {
  //   key: "behavior-abc",
  //   label: "Behavior (ABC)",
  //   navKey: "behaviorAbc",
  //   path: "/behavior-abc",
  //   icon: Activity,
  //   rolesAllowed: [ROLES.PARENT, ROLES.TEACHER_THERAPIST, ROLES.ADMIN],
  // },
  {
    key: "contact-log",
    label: "Contact Log",
    navKey: "contactLog",
    path: "/contact-log",
    icon: MessageSquare,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.TEACHER_THERAPIST, ROLES.ADMIN],
  },
  {
    key: "letter-writer",
    label: "Letter Writer",
    navKey: "letterWriter",
    path: "/letter-writer",
    icon: Mail,
    rolesAllowed: [ROLES.PARENT, ROLES.ADMIN],
  },
  {
    key: "advocacy-lab",
    label: "Advocacy Lab",
    navKey: "advocacyLab",
    path: "/advocacy-lab",
    icon: Scale,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.ADMIN],
  },
  {
    key: "compliance",
    label: "Compliance",
    navKey: "compliance",
    path: "/compliance",
    icon: CheckSquare,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.ADMIN],
  },
  {
    key: "legal-support",
    label: "Rights & Resources",
    navKey: "legalSupport",
    path: "/legal-support",
    icon: Gavel,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.ADMIN],
  },
  {
    key: "resources",
    label: "Resources",
    navKey: "resources",
    path: "/resources",
    icon: BookOpen,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.TEACHER_THERAPIST, ROLES.COUNSELOR, ROLES.ADMIN],
  },
  {
    key: "expert-consultation",
    label: "Expert Consultation",
    navKey: "expertConsultation",
    path: "/expert-consultation",
    icon: UserCircle,
    rolesAllowed: [ROLES.PARENT, ROLES.ADMIN],
  },
  {
    key: "admin-users",
    label: "User Management",
    navKey: "userManagement",
    path: "/admin/users",
    icon: Users,
    rolesAllowed: [ROLES.ADMIN],
  },
  {
    key: "admin-analytics",
    label: "User Analytics",
    navKey: "adminAnalytics",
    path: "/admin/analytics",
    icon: BarChart3,
    rolesAllowed: [ROLES.ADMIN],
  },
  {
    key: "admin-plans",
    label: "Subscription Plans",
    navKey: "adminPlans",
    path: "/admin/plans",
    icon: CreditCard,
    rolesAllowed: [ROLES.ADMIN],
  },
  {
    key: "billing",
    label: "Billing",
    navKey: "billing",
    path: "/billing",
    icon: CreditCard,
    rolesAllowed: [ROLES.PARENT],
  },
  {
    key: "settings",
    label: "Settings",
    navKey: "settings",
    path: "/settings",
    icon: Settings,
    rolesAllowed: [ROLES.PARENT, ROLES.ADVOCATE, ROLES.TEACHER_THERAPIST, ROLES.ADMIN],
  },
];
